trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Tasks/*

parameters:
- name: publishPreview
  displayName: Publish preview extension
  type: boolean
  default: true
- name: testPreview
  displayName: Test preview tasks
  type: boolean
  default: false

variables:
- template: templates/variables.yml

stages:
- stage: Build
  jobs:
  - job: Task
    pool:
      name: Default
    workspace:
      clean: all
    steps:
    - template: templates/build.yml
      parameters:
        name: ${{ variables.taskName }}
        path: ${{ variables.tasksPath }}
        restore: true
        lint: true
        build: true
        test: true
        clean: true
        publish: true
  - job: Extension
    pool:
      name: Default
    workspace:
      clean: all
    dependsOn:
    - Task
    steps:
    - template: templates/package.yml
      parameters:
        path: ${{ variables.artifactsPath }}
        contents: |
          Images/**
          LICENSE
          *.md
          *.json
        version: ${{ variables.version }}
        publish: true

- stage: Preview
  dependsOn:
  - Build
  jobs:
  - ${{ if eq(parameters.publishPreview, true) }}:
    - job: Publish
      pool:
        name: Default
      workspace:
        clean: all
      steps:
      - template: templates/publish.yml
        parameters:
          path: ${{ variables.extensionArtifactPath }}
          endpointName: ${{ variables.marketplaceEndpoint }}
          visibility: ${{ variables.extensionPreviewVisibility }}
          shareWith: ${{ variables.extensionPreviewShareWith }}
          tag: preview
  - ${{ if eq(parameters.testPreview, true) }}:
    - job: Test
      pool:
        name: Default
      workspace:
        clean: all
      ${{ if eq(parameters.publishPreview, true) }}:
        dependsOn:
        - Publish
      steps:
      - template: templates/test.yml
        parameters:
          endpoint: ${{ variables.testEndpoint }}
          network: ${{ variables.testNetwork }}
          urls: ${{ variables.testUrls }}
          purgeMethod: ${{ variables.purgeMethod }}

- stage: Release
  dependsOn:
  - Build
  - Preview
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: Publish
    pool:
      name: Default
    workspace:
      clean: all
    environment: Marketplace
    strategy:
      runOnce:
        deploy:
          steps:
          - template: templates/publish.yml
            parameters:
              path: ${{ variables.extensionArtifactPath }}
              endpointName: ${{ variables.marketplaceEndpoint }}
              visibility: ${{ variables.extensionVisibility }}
              shareWith: ${{ variables.extensionShareWith }}
